---
- name: Prepare servers
  hosts: all
  become: true

  vars:
    pip_install_packages:
      - name: docker
    docker_install_compose_plugin: false

  roles:
    - role: geerlingguy.pip
    - role: geerlingguy.docker

- name: Deploy Redmine
  hosts: all
  become: true

  vars:
    redmine_dir: /opt/redmine

  tasks:
    - name: Create Redmine directory
      ansible.builtin.file:
        path: "{{ redmine_dir }}"
        state: directory
        mode: "0755"

    - name: Create Redmine env file
      ansible.builtin.template:
        src: templates/redmine.env.j2
        dest: "{{ redmine_env_file }}"
        mode: "0644"

    - name: Run Redmine container
      community.docker.docker_container:
        name: "{{ redmine_container_name }}"
        image: "{{ redmine_image }}"
        state: started
        restart_policy: always
        pull: true
        recreate: true
        published_ports:
          - "{{ redmine_port }}:3000"
        env_file: "{{ redmine_env_file }}"

- name: Configure Datadog monitoring
  hosts: webservers
  become: true

  roles:
    - role: datadog.dd.agent
